#!/bin/sh

# Gradle Wrapper for Unix
# Auto-generated by gradle wrapper

export JAVA_HOME="${JAVA_HOME:-}"
export GRADLE_OPTS="${GRADLE_OPTS:-}"

# Resolve the location of the Gradle installation.
PRG="$0"
while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done
DIRNAME=`dirname "$PRG"`

# Use JAVA_HOME if set, otherwise look for java in PATH
if [ -n "$JAVA_HOME" ]; then
  JAVA_EXE="$JAVA_HOME/bin/java"
else
  JAVA_EXE=java
fi

# Check if java is available
"$JAVA_EXE" -version > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "ERROR: Java not found. Please install Java or set JAVA_HOME."
  exit 1
fi

# Execute Gradle
exec "$JAVA_EXE" $GRADLE_OPTS -classpath "$DIRNAME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"